import argparse
import yaml
from collections import namedtuple

Param = namedtuple('Param', [
    'name',
    'default'
])

Method = namedtuple('Method', [
    'function_name',
    'method_name',
    'params'
])

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--methods_yaml_fn',   '-y', default='data/methods.yaml')
    parser.add_argument('--methods_module_fn', '-m', default='src/lastfmget/raw_methods.py')
    args = parser.parse_args()

    with open(args.methods_yaml_fn, 'r') as f:
        methodsyaml = yaml.safe_load(f)

    methods = get_methods_list(methodsyaml)
    methodsmoduletext = get_methods_module_str(methods, args.methods_yaml_fn)

    with open(args.methods_module_fn, 'w') as f:
        f.write(methodsmoduletext)

def get_methods_list(methodsyaml):
    methods = []

    paramdefaults = methodsyaml['param_defaults'] # dict
    methodgroups  = methodsyaml['groups'] # dict

    for group, groupdata in methodgroups.items(): # str, dict
        groupparams  = groupdata['common_params'] # list
        groupmethods = groupdata['methods'] # list

        for method in groupmethods: # dict
            functionname = f'{group}_{method["function"]}'
            methodname   = f'{group}.{method["method"]}'
            methodparams = method['params'] # list

            paramnames = groupparams + methodparams
            params = [ Param(name, paramdefaults[name]) for name in paramnames ]

            methods.append(Method(functionname, methodname, params))

    return methods
            
def get_methods_module_str(methods, srcfn):
    lines = []

    src = srcfn.replace("\\", "/")
    lines.append('"""')
    lines.append('Thin wrappers around Last.fm API methods.')
    lines.append('')
    lines.append(f'* Module generated by gen_raw_methods_module.py from {src}')
    lines.append('"""')
    lines.append('from .core import __get_response')
    lines.append('')

    for method in methods:
        methodstr = get_method_str(method)
        lines.append(methodstr)
        lines.append('')
    
    return '\n'.join(lines)

def get_method_str(method):
    lines = []

    methodargs = [
        f'{param.name}={param.default}' if param.default is not None else param.name
        for param in method.params
    ]
    argstring = ', '.join(methodargs)

    payload = { wrap_str('method'): wrap_str(method.method_name) }
    for param in method.params:
        payload[wrap_str(param.name)] = param.name

    alignwidth = max(len(key) + 1 for key in payload.keys())

    lines.append(f'def {method.function_name}_raw({argstring}):')
    lines.append(f'    """{method.method_name}"""')
    lines.append('    payload = {')

    for i, (key, val) in enumerate(payload.items()):
        lines.append(f'        {key:<{alignwidth}}: {val}{"," if i < len(payload)-1 else ""}')

    lines.append('    }')
    lines.append('    return __get_response(payload)')

    return '\n'.join(lines)

def wrap_str(s):
    return "'" + s + "'"

if __name__ == '__main__':
    main()
